import js from '@eslint/js';
import prettier from 'eslint-config-prettier/flat';
import { createTypeScriptImportResolver } from 'eslint-import-resolver-typescript';
import importX from 'eslint-plugin-import-x';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * Selectors that mechanise the "hard rules" table in AGENTS.md.
 *
 * Every rule in AGENTS.md must appear here or be deleted from AGENTS.md.
 * A rule that only exists in prose is advice, and agents drop advice under
 * context pressure.
 */
export const RESTRICTED_SYNTAX = {
  rawHexColor: {
    selector: 'Literal[value=/^#(?:[0-9a-fA-F]{3,4}){1,2}$/]',
    message:
      'Raw hex colour. Use a token: `bg-primary` / `text-muted-foreground`, or add the colour to packages/tokens/src/tokens.ts first.',
  },
  rawFunctionalColor: {
    selector: 'Literal[value=/^(?:rgba?|hsla?)\\(/]',
    message:
      'Raw colour function. Use a token from packages/tokens/src/tokens.ts — colours must exist in exactly one place.',
  },
  rawJsxText: {
    selector: 'JSXText[value=/[A-Za-z]{3,}/]',
    message:
      'User-facing string in JSX. Wrap it in t() from @repo/core/i18n so it is translatable (audit 13.2).',
  },
};

export const RESTRICTED_GLOBALS = [
  {
    name: 'localStorage',
    message:
      'Never touch localStorage directly. The session is persisted in exactly one place — apps/web/src/lib/storage.ts, the only file with an override for this rule — and everything else goes through the storage adapter passed to configureCore(). Adding a second call site puts a credential somewhere nothing is watching.',
  },
  {
    name: 'sessionStorage',
    message: 'Use the storage adapter passed to configureCore() instead of sessionStorage.',
  },
];

/**
 * The shared spine. Every package extends this.
 *
 * @param {object} options
 * @param {string} options.tsconfigRootDir - pass `import.meta.dirname`
 * @returns {import('typescript-eslint').ConfigArray}
 */
export function baseConfig({ tsconfigRootDir }) {
  return tseslint.config(
    {
      ignores: [
        '**/dist/**',
        '**/build/**',
        '**/coverage/**',
        '**/.turbo/**',
        '**/.expo/**',
        '**/node_modules/**',
        // Config files run in Node before any transform, are CJS or bare ESM, and
        // are not part of any tsconfig project — so typed linting cannot see them.
        '**/*.config.js',
        '**/*.config.cjs',
        '**/*.config.mjs',
        // Generated by `pnpm tokens:sync` and `msw init`.
        '**/global.css',
        '**/mockServiceWorker.js',
      ],
    },

    js.configs.recommended,
    // Type-aware linting. `no-floating-promises` / `no-misused-promises` /
    // `await-thenable` are the highest-value rules in the whole config for
    // agent-written async code, and they only exist with type information.
    tseslint.configs.recommendedTypeChecked,

    {
      languageOptions: {
        parserOptions: {
          // projectService (not `project: [...]`) is the current
          // typescript-eslint recommendation and the only one that handles
          // monorepo project references without hand-maintained globs.
          projectService: true,
          tsconfigRootDir,
        },
      },
      settings: {
        'import-x/resolver-next': [
          createTypeScriptImportResolver({ alwaysTryTypes: true, project: tsconfigRootDir }),
        ],
      },
      plugins: { 'import-x': importX },
      rules: {
        // --- the two rules the house has always enforced ---
        '@typescript-eslint/no-explicit-any': 'error',
        'no-console': 'error',

        // --- type safety ---
        '@typescript-eslint/consistent-type-imports': [
          'error',
          { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
        ],
        '@typescript-eslint/no-unused-vars': [
          'error',
          { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
        ],
        '@typescript-eslint/no-non-null-assertion': 'error',
        '@typescript-eslint/no-unnecessary-condition': 'warn',
        '@typescript-eslint/switch-exhaustiveness-check': 'error',

        // --- correctness ---
        eqeqeq: ['error', 'always', { null: 'ignore' }],
        'no-restricted-globals': ['error', ...RESTRICTED_GLOBALS],
        'no-restricted-syntax': [
          'error',
          RESTRICTED_SYNTAX.rawHexColor,
          RESTRICTED_SYNTAX.rawFunctionalColor,
        ],

        // --- imports ---
        // tsc already reports unresolved imports, and running the resolver over
        // every specifier is the slowest part of the lint. Don't pay twice.
        'import-x/no-unresolved': 'off',
        'import-x/no-cycle': ['error', { maxDepth: 4, ignoreExternal: true }],
        'import-x/no-duplicates': 'error',
        // The price of `nodeLinker: hoisted` is that any package can physically
        // resolve any other package's dependencies. This is what stops that
        // turning into undeclared runtime deps.
        'import-x/no-extraneous-dependencies': [
          'error',
          {
            devDependencies: [
              '**/*.test.{ts,tsx}',
              '**/*.spec.{ts,tsx}',
              '**/__tests__/**',
              '**/test/**',
              '**/scripts/**',
              '**/*.config.{ts,js,mjs}',
              '**/vitest.config.ts',
              // apps/web/src/mocks/* only ever imports msw and @repo/mocks
              // dynamically, behind a VITE_ENABLE_MOCKS guard, so neither ends
              // up in the production bundle.
              '**/mocks/**',
            ],
            // Type-only imports are erased at build time, so they cannot create
            // the runtime phantom dependency that `nodeLinker: hoisted` risks —
            // which is the entire reason this rule is on. Checking them would
            // only generate friction over `import type { Config } from
            // 'tailwindcss'` in config files.
            includeTypes: false,
          },
        ],
        'import-x/order': [
          'error',
          {
            groups: [
              'builtin',
              'external',
              'internal',
              'parent',
              'sibling',
              'index',
              'object',
              'type',
            ],
            pathGroups: [
              { pattern: 'react', group: 'external', position: 'before' },
              { pattern: 'react-dom{,/**}', group: 'external', position: 'before' },
              { pattern: 'react-native', group: 'external', position: 'before' },
              { pattern: 'expo{,-*}{,/**}', group: 'external', position: 'before' },
              { pattern: '@repo/**', group: 'internal' },
              { pattern: '@/**', group: 'internal', position: 'after' },
              { pattern: '~/**', group: 'internal', position: 'after' },
            ],
            pathGroupsExcludedImportTypes: ['react', 'react-native', 'type'],
            'newlines-between': 'always',
            alphabetize: { order: 'asc', caseInsensitive: true },
          },
        ],
      },
    },

    // Plain JS — the repo-root Node scripts (scripts/*.mjs) and any .cjs shim.
    //
    // Type-aware linting cannot apply to these: they are not in any tsconfig
    // program (`allowJs` is false everywhere except expo.json, so the
    // `scripts/**/*.mjs` entry in the root tsconfig's `include` is inert), and
    // projectService fails them outright with "was not found by the project
    // service". Turning `allowJs` on instead is worse — it drags untyped
    // JSON-import-heavy scripts into every no-unsafe-* rule.
    //
    // This only ever surfaced through lint-staged: `turbo lint` runs per package
    // and nothing lints the repo root, so the parse error was invisible until the
    // first commit tried to run the pre-commit hook.
    {
      files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
      ...tseslint.configs.disableTypeChecked,
      languageOptions: {
        ...tseslint.configs.disableTypeChecked.languageOptions,
        // Without these, `no-undef` (on for JS, off for TS via tseslint's
        // eslint-recommended override) flags every `process` and `console`.
        globals: { ...globals.node },
      },
    },

    // Tests get to be pragmatic. Type-aware strictness on assertions produces
    // noise that teaches people to disable rules.
    {
      files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}', '**/__tests__/**', '**/test/**'],
      rules: {
        '@typescript-eslint/no-non-null-assertion': 'off',
        '@typescript-eslint/no-unsafe-assignment': 'off',
        '@typescript-eslint/no-unsafe-member-access': 'off',
        '@typescript-eslint/no-unnecessary-condition': 'off',
        'no-restricted-syntax': 'off',
      },
    },

    // Node-side scripts legitimately write to stdout.
    //
    // They also legitimately contain colour strings: assert-css-output.mjs asserts
    // that the GENERATED css contains `hsl(var(--primary) / .9)`, so the raw-colour
    // rule would fire on the very literal the check exists to look for. The rule
    // protects shipped UI code, which is not what these files are.
    {
      files: ['**/scripts/**', '**/*.config.{ts,mts}', '**/server.ts'],
      rules: { 'no-console': 'off', 'no-restricted-syntax': 'off' },
    },

    // MUST be last: turns off every rule that would fight Prettier.
    prettier,
  );
}
